# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\robot-arm\Documents\pictureline_display\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(662, 642)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.image_path_label = QtGui.QLabel(self.centralWidget)
        self.image_path_label.setObjectName(_fromUtf8("image_path_label"))
        self.verticalLayout_3.addWidget(self.image_path_label, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.image_path_lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.image_path_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.image_path_lineEdit.setObjectName(_fromUtf8("image_path_lineEdit"))
        self.verticalLayout_3.addWidget(self.image_path_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.noise_combo = QtGui.QComboBox(self.centralWidget)
        self.noise_combo.setMinimumSize(QtCore.QSize(180, 0))
        self.noise_combo.setObjectName(_fromUtf8("noise_combo"))
        self.verticalLayout.addWidget(self.noise_combo)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.blur_combo = QtGui.QComboBox(self.centralWidget)
        self.blur_combo.setMinimumSize(QtCore.QSize(180, 0))
        self.blur_combo.setObjectName(_fromUtf8("blur_combo"))
        self.verticalLayout.addWidget(self.blur_combo)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.open_image_button = QtGui.QPushButton(self.centralWidget)
        self.open_image_button.setMinimumSize(QtCore.QSize(100, 0))
        self.open_image_button.setObjectName(_fromUtf8("open_image_button"))
        self.verticalLayout_2.addWidget(self.open_image_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.save_plot_button = QtGui.QPushButton(self.centralWidget)
        self.save_plot_button.setMinimumSize(QtCore.QSize(100, 0))
        self.save_plot_button.setObjectName(_fromUtf8("save_plot_button"))
        self.verticalLayout_2.addWidget(self.save_plot_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 240))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.picture_display = QtGui.QLabel(self.frame)
        self.picture_display.setText(_fromUtf8(""))
        self.picture_display.setObjectName(_fromUtf8("picture_display"))
        self.horizontalLayout_2.addWidget(self.picture_display)
        self.y_verticalSlider = QtGui.QSlider(self.frame)
        self.y_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.y_verticalSlider.setObjectName(_fromUtf8("y_verticalSlider"))
        self.horizontalLayout_2.addWidget(self.y_verticalSlider)
        self.verticalLayout_4.addWidget(self.frame)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_info_display = QtGui.QVBoxLayout()
        self.line_info_display.setMargin(11)
        self.line_info_display.setSpacing(6)
        self.line_info_display.setObjectName(_fromUtf8("line_info_display"))
        self.horizontalLayout_3.addLayout(self.line_info_display)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 662, 17))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.image_path_label.setText(_translate("MainWindow", "图片路径", None))
        self.label_2.setText(_translate("MainWindow", "噪点", None))
        self.label_3.setText(_translate("MainWindow", "模糊", None))
        self.open_image_button.setText(_translate("MainWindow", "打开图片", None))
        self.save_plot_button.setText(_translate("MainWindow", "保存曲线", None))

